"""add created for user

Revision ID: 6126ad9514aa
Revises: 673303a696bb
Create Date: 2018-06-09 10:31:56.159846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6126ad9514aa'
down_revision = '673303a696bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created')
    # ### end Alembic commands ###
