"""delete created for user

Revision ID: 6e71c29e6611
Revises: 6126ad9514aa
Create Date: 2018-06-09 10:41:35.911735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e71c29e6611'
down_revision = '6126ad9514aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
